### ISSUE TITLE
Dark-mode CSS update changes layout

### ISSUE THREAD

**Issue by ardgedee** [MLTSHP/mltshp-patterns#260]
The CSS changes that came over with the Dark Mode update have also apparently affected page layout. I've asked for details about browser and OS.

https://mltshp.com/p/1JY8D
https://mltshp.com/p/1JY8F
https://mltshp.com/p/1JY8G

**Comment by spaceninja** [comment]
Reading the comments, it seems the issue people are most concerned with is increased line-height, especially in descriptions and titles. We're currently using `1.4` globally, we could explore dropping it to `1.3` globally, and should definitely drop to `1.1` for titles.

**Comment by jessamynwest** [comment]
Yeah the line height thing is something I'd prefer to be a little tighter. I also think the font on comments is 1. smaller 2. smaller than the descriptions but only by a tiny amount. My impression is that they matched before (could be wrong!) and what I'd like is for them to still match.

**Comment by jessamynwest** [comment]
Have been interacting with this for a week and the lightness/smallness of the comment font is really continuing to be jarring so I think needs a little boosting.

**Comment by spaceninja** [comment]
(sorry, hit the wrong button, didn't mean to close this)
